### PR TITLE
Refactor rlay-client-lib and make tests pass

### LINKED ISSUE #63: Error on unknown property usage in rlay-client-lib
Follow up to #1: https://github.com/rlay-project/rlay-utils/pull/1#issuecomment-497276122
> When passing a seemingly unknown property, it just ignores that silently and creates an empty Individual

### LINKED ISSUE #64: Different property values on Individual.create yield the same CID
Follow up to #1 .

Repo to reproduce: https://github.com/hobofan/rlay-utils-repro/tree/fe349c4ca80ec79c22b2b2200ab9ac1c96a63d8f

### LINKED ISSUE #66: Set up rlay-client-lib testing in Travis and add to dependabot

### LINKED ISSUE #78: rlay-client-lib devDependency should be a path
Not 100% sure, but I think the `rlay-client-lib` devDependency should be a path dependency to the directory, which would help with keeping it in sync.

See: 
https://github.com/rlay-project/rlay-utils/blob/cf5ddf68d034879ef1a9c335a9d8758d44084725/package.json#L59

Related: #70

### LINKED ISSUE #83: add more tests for `Individual.assert`

### LINKED ISSUE #84: add support/tests for multiple {Data,Object}PropertyAssertions
At the moment there are no tests that guarantee that multiple assertions of the same Data- or ObjectProperty but with different values are supported. My guess is, it doesn't work yet. But e.g. for `rlay-transform` it is important that it works.

### Create/Assert

this is not tested but educated guess is, that it should work:

```js
await person.assert({
  favoriteAnimals: 'horse',
  favoriteAnimals: 'deer'
});
```

but add support for this as well

```js
await person.assert({
  favoriteAnimals: ['horse', 'deer']
});
```

### Resolve

Assume we created/asserted an individual like this:

```js
await person.assert({
  favoriteAnimals: 'horse',
  favoriteAnimals: 'deer'
});
```

then `await person.resolve()` most likely won't give the desired output and will just be

```js
assert.equal(person.favoriteAnimals, 'deer');
```

but should be

```js
assert.deepEqual(person.favoriteAnimals, ['horse', 'deer']);
```

### LINKED ISSUE #85: add support/tests for Negative{Class,Data,Object}PropertyAssertions
May work already, but is not yet tested.

Is a prerequisite for aggregating over assertions that are contradicting each other.

### LINKED ISSUE #105: Bug: non properties returned when ObjectPropertyAssertions
calling `individual.resolve()` results in `individual.properties` including non-properties if that individual was used as `target` in an `ObjectPropertyAssertion`.

Problems seems to be in the neo4j query

### PR DESCRIPTION
**Pull request by MichaelHirn**
- [x] CLOSES: #63 
- [x] CLOSES: #64 
- [x] CLOSES: #66 
- [x] CLOSES: #83 
- [x] CLOSES: #84 
- [x] CLOSES: #85 
- [x] CLOSES: #78 
- [x] CLOSES: #105

### CODE REVIEW

**Comment by MichaelHirn** [comment]
4b071f8 adds `Payload` class, refactors `EntityInterface`, makes tests pass, but takes some to-be-done tests out for now

**Comment by MichaelHirn** [comment]
@hobofan I also added integration tests (e.g. to test against #64) but travis doesn't pick those up automatically right?

**Comment by hobofan** [comment]
Not automatically, but you can add it to the `.travis.yml`.

**Comment by MichaelHirn** [comment]
[This](https://github.com/rlay-project/rlay-utils/blob/master/.travis.yml) is the only `.travis.yml`? It already specifies the unit and integration tests, but I'm not sure how that applies to `rlay-client-lib`

**Comment by hobofan** [comment]
LGTM! Finally had time to test it, and not running into any errors and it's quite intuitive! Great work 🎉 👏

**Pull request merged**
