### PR TITLE
feat/findByAssertion: add Rlay_Individual.findByAssertion

### PR DESCRIPTION
**Pull request by MichaelHirn**
Allows for

```js
await rlayClient.Individual.findByAssertion({customDataProperty: 123});
```

and returns

```js
{
  properties: [Rlay_Individual, Rlay_Individual] // all Individuals with that assertion as a property
  assertions: [Rlay_Individual] // all individuals with that assertion as a real assertion
}
```

### CODE REVIEW

**Review by hobofan — APPROVED** [review]

**Comment by hobofan** [comment]
Looks good overall. My only suggestion would be to rename the fields in the response object to make their meaning a bit more obvious:

```
{
  withProperty: [Rlay_Individual, Rlay_Individual] // all Individuals with that assertion as a property
  withAssertion: [Rlay_Individual] // all individuals with that assertion as a real assertion
}
```

**Comment by MichaelHirn** [comment]
Trying to use it in the wild, I realized finding the individuals for non-property assertions (i.e. those made with `.assert()`) do not work with the current setup.

Currently it computes the `cid` of the assertion and then searches via a cypher query for the Individuals that are the ~subject for that assertion. However, for non-property assertions that doesn't work because you need to know the subject `cid` otherwise the assertion `cid` that you are computing is meaningless.

So to make it work for non-property assertions as well I have to change the cypher and start by the schema properties (`Class`, `DataProperty`, `ObjectProperty`).

Commits for this coming ...

**Comment by MichaelHirn** [comment]
It is tested now for both assertions and properties for Class, DP, and OP assertions.

Performance decreased by a not insignificant amount as there isn't a single index it can hit and it has to do almost twice the amount of hops (which neo isn't that good at). It also varied quite strongly for me locally from ~50ms up to ~500ms. Not sure if there is anything we can do here though. DB was also tiny with just a few hundred nodes and relationships so not sure how well this will scale.

`.findByAssertion` might not work very well atm for assertions that return really large results and only works for a single assertion atm. Getting it to work for multiple assertions is blocked by only the cypher query though. My add this later if I hit a use-case for it.

**Comment by MichaelHirn** [comment]
renamed it to `.asProperty` and `.asAssertion` as I thought that is closer how you would describe it.

> Used the assertion as Property Assertion and as Assert Assertion

**Comment by MichaelHirn** [comment]
@hobofan will merge tomorrow if you want to have another look over it

**Comment by MichaelHirn** [comment]
I guess the need for multiple assertions arose earlier than expected lol

You can pass in multiple assertions now, which means it tries to find entities for which all of them match (AND concatenated).

Once travis passed I will merge and close. Still needs to be reviewed in the main feature PR

**Pull request merged**
