### PR TITLE
Add getEntityCid from @rlay/ontology

### PR DESCRIPTION
**Pull request by MichaelHirn**
This PR introduces the `getEntityCid` function to the client module and slims the Entity interface from

```javascript
const entity = new Entity(client, payload, cid);
```

to 

```javascript
const entity = new Entity(client, payload);
```

as the `CID` can now be computed on site from the payload.

This works for any valid payload, however, it is current practice to use `*` references in the schema files, which serve as input for the `client`, for example when used with `rlay-generate`. To stay backward compatible, it will work (although no CIDs can be computed) but will generate deprecation warnings.

To use this new feature, update your schema files to use the `CID` instead of a `*` reference.

Suggestion to make this PR part of the upcoming `v0.2.0`

### CODE REVIEW

**Comment by MichaelHirn** [comment]
published as `@rlay/rlay-client-lib@0.2.0-pre.3`

**Comment by hobofan** [comment]
I don't understand the comment about the `*` references. I'd really like to continue to support them going forward.

With the `getEntityCid` method, it should also be pretty easy to create a 1:1 mapping from aliases to entities, since getting the CID is not async anymore.

**Comment by MichaelHirn** [comment]
I'm a bit worried about supporting multiple ways of defining the schemas. It would also require some special logic in the client to deserialize the referenced entities and construct the correct tree, etc. which is not untrivial. What's the advantage of keeping `*` references?

The change in the seed files would basically be:

```javascript
module.exports = {
  httpRequestClassDescription: new client.Rlay_Annotation(client, { ... })
  httpRequestClass: new client.Rlay_Class(client, {
    annotations: ['*httpRequestClassDescription']
  });
}
```

to 

```javascript
const httpRequestClassDescription = new client.Rlay_Annotation(client, { ... });

const httpRequestClass = new client.Rlay_Class(client, {
  annotations: [httpRequestClassDescription.cid]
});

module.exports = {
  httpRequestClassDescription,
  httpRequestClass
}
```

**Comment by hobofan** [comment]
The advantage would be that seedfiles can stay human-editable and also pretty human-readable.

If specifying a CID is a hard requirement, then it becomes much harder to evaluate if a schema is roughly correct just by looking at it. Editing a single value would also mean that you need to copy-paste the value elsewhere to generate the CID and then paste it back.

Involving the client in seedfiles (which would be a way to calculate the CIDs on the fly, as in your example), would then also become a de-facto requirement to using seedfiles, which I don't think is a good idea. The seedfiles should in general be data-only and the JS-variant only a help to more easily construct seedfiles.

In my opinon the lifecycle of a seedfile should be:

JS-seedfile (and in the future hopefully other languages) ----evaluation--> seedfile (with references) -----dereferencing/calculating CIDs----> flat seedfile, which can be used as an input to `rlay-seed`, `rlay-generate`, etc.

With that, you also wouldn't need any special resolver logic inside the client.

**Comment by MichaelHirn** [comment]
I get that and I think that makes total sense. I agree that a higher-level language makes sense and the strong requirement for the client is a bit problematic.

In my opinion, the lifecycle would be the following. With small functions that carry one representation to the next.

Question: I have the feeling we are agreeing that either way the `client` should not have to deal with anything other than proper Rlay payloads (plain Objects) - so we leave the deprecation notice?

#### Rlay Client Schema Objects

`Rlay Client Schema Objects` > Flat Seed File (Plain Objects); input for `rlay-seed`, ...

#### Rlay Schema Definition Language (RSDL)

`RSDL file(s)` > `Rlay Client Schema Objects` > Flat Seed File (Plain Objects); input for `rlay-seed`, ...

### Examples

#### RSDL

Comparable to `GraphQL Schema Definition Language`

> This format is completely made up

```
Class "HttpRequest"
  annotations:
    Annotation "*HttpRequestDescription"
      ...
  superClass: "HttpConnection"
```

#### Rlay Client Schema Objects

Comparable to `GraphQL.js GraphQLSchema object`

```javascript
const HttpRequest = client.Rlay_Class({ ....
```

#### Flat Seed File (Plain Objects)

```javascript
[
  {
     type: 'Class'
     ....
  },
  { ... },
  ...
]
```

**Comment by hobofan** [comment]
> Question: I have the feeling we are agreeing that either way the client should not have to deal with anything other than proper Rlay payloads (plain Objects) - so we leave the deprecation notice?

Yes, that sounds reasonable. If someone really wants to use the client in a seedfile, that should be possible, even though I think that's overkill for developing a schema. I think in that case it would be good to have a function available that allows a tree to be dereferenced, so that switching between the two formats becomes more seamless.

The RSDL looks like what we already have with seedfiles in a primitive version (just with a fancier format), and would bring the exact same challenges with it when transforming it into Rlay Client Schema Objects.

**Comment by MichaelHirn** [comment]
> The RSDL looks like what we already have with seedfiles in a primitive version (just with a fancier format) and would bring the exact same challenges with it when transforming it into Rlay Client Schema Objects.

Yeah exactly, the RSDL can also be much simpler of course (e.g. only `*` references) or even more complex or whatever.

But either way, I think we are on the same page then in terms of the different formats and switching between them.

Feel free to review/merge etc.

**Pull request merged**
